# Generated by Django 5.2.7 on 2025-11-20 12:23

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_address',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dti_office',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Only applicable if the user is a collection agent.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='official_designation',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Only applicable if the user is a collection agent.', null=True),
        ),
    ]
